-- +goose Up
ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS track_number VARCHAR(50),
    ADD COLUMN IF NOT EXISTS entry VARCHAR(10),
    ADD COLUMN IF NOT EXISTS delivery JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS payment JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS items JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS locale VARCHAR(10),
    ADD COLUMN IF NOT EXISTS internal_signature VARCHAR(100),
    ADD COLUMN IF NOT EXISTS customer_id VARCHAR(50),
    ADD COLUMN IF NOT EXISTS delivery_service VARCHAR(50),
    ADD COLUMN IF NOT EXISTS shardkey VARCHAR(10),
    ADD COLUMN IF NOT EXISTS sm_id INTEGER,
    ADD COLUMN IF NOT EXISTS date_created TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS oof_shard VARCHAR(10);

ALTER TABLE orders
    DROP COLUMN IF EXISTS data;


-- +goose Down
ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS data JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE orders
    DROP COLUMN IF EXISTS track_number,
    DROP COLUMN IF EXISTS entry,
    DROP COLUMN IF EXISTS delivery,
    DROP COLUMN IF EXISTS payment,
    DROP COLUMN IF EXISTS items,
    DROP COLUMN IF EXISTS locale,
    DROP COLUMN IF EXISTS internal_signature,
    DROP COLUMN IF EXISTS customer_id,
    DROP COLUMN IF EXISTS delivery_service,
    DROP COLUMN IF EXISTS shardkey,
    DROP COLUMN IF EXISTS sm_id,
    DROP COLUMN IF EXISTS date_created,
    DROP COLUMN IF EXISTS oof_shard;
